# titre du workflow
name: Mon premier test
# On indique le déclencheur
# push
# pull
# merge
# au push sur branche ...
on: 
  push:
    branches:
      - dev # preuve que ça ne marche pas sur main
# ensuite on déclare des processus de travail, des routines.
jobs:
  # on donne un nom à notre job
  exploration:
    runs-on: ubuntu-latest # on peut aussi avoir l'option debian, windows ou macos par exemple
    # on déclare les tâches que notre processus va exécuter
    steps:
      - run: echo "Salut"
      - name: Reponse Salut
        run: echo "Salut Jean Mich"
      - run: echo "TG"

  toto:
    runs-on: ubuntu-latest
    steps:
      - name : Récupération du exploration
        uses: actions/checkout@v3 # on cible ici un repository sur github actions qui s'appelle checkout
        # ce repository permet d'utiliser certains mots clés https://github.com/actions/checkout
      - name : "Lister les contenus du dossier de mon test"
        run: ls 
  
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: je fais des tests
        run: echo "je fais des tests"
    
  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
        - name: je fais le build
          run: echo "je fais le build"

      
